# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our issue template. Please read it."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the bug"
  - "To Reproduce"
  - "Steps to Reproduce"
  - "Expected behavior"
  - "Screenshots"
  - "Desktop"
  - "Smartphone"
  - "Additional context"
- content:
# Example 2: feature request
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd liker"
  - "Describe alternatives you've considered"
  - "Additional context"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
